'use client';

import React from 'react';
import {
  Check,
  Sparkles,
  Gauge,
  Layers,
  Timer,
  Activity,
  Crosshair,
  ListChecks,
} from 'lucide-react';
import type { ReportData } from '@/lib/utils';
import { pct, ms, mb, params, flops, int, MODEL_COLORS } from '@/lib/utils';
import { REPORT_ORDER } from '@/lib/researchService';
import { MetricRadar } from '@/components/charts/RadarChart';
import { LatencyDistributionChart, ThroughputChart } from '@/components/charts/LatencyChart';
import { ConfusionMatrix } from '@/components/charts/ConfusionMatrix';
import { AccuracyChart, EfficiencyChart, type ComparisonPoint } from '@/components/charts/ModelComparison';
import { cn } from '@/lib/utils';

interface Props {
  reports: ReportData[];
  loading: boolean;
  selectedName: string;
  onSelectName: (name: string) => void;
}

export function ResearchSection({ reports, loading, selectedName, onSelectName }: Props) {
  const selected = reports.find((r) => r.metadata.model_name === selectedName) ?? reports[0];

  const meta = (name: string) => REPORT_ORDER.find((m) => m.name === name);

  const comparisonPoints: ComparisonPoint[] = reports.map((r) => ({
    name: meta(r.metadata.model_name)?.label ?? r.metadata.model_name,
    accuracy: r.model_evaluation.accuracy * 100,
    f1: r.model_evaluation.f1_score * 100,
    latency: r.summary.latency_performance.single_sample_latency_ms,
    size: r.complexity_analysis.memory_size.int8_mb * 1024,
    params: r.complexity_analysis.parameters.total_parameters,
  }));

  const throughputData = reports.map((r) => ({
    name: meta(r.metadata.model_name)?.label ?? r.metadata.model_name,
    throughput: r.summary.latency_performance.throughput_samples_per_sec,
  }));

  return (
    <div className="space-y-14 pb-16">
      {/* Intro */}
      <div className="mx-auto max-w-3xl text-center">
        <p className="inline-flex items-center gap-2 rounded-full border border-rose-100 bg-rose-50 px-4 py-1.5 text-xs font-medium text-rose-600">
          <Sparkles className="h-3.5 w-3.5" /> Benchmark Analysis · AAMI EC57 Compliant
        </p>
        <h1 className="mt-5 text-3xl font-bold tracking-tight text-slate-900 sm:text-4xl">
          Research analysis &amp; optimization trade-offs
        </h1>
        <p className="mt-4 text-lg leading-relaxed text-slate-600">
          Every metric below is generated by the Beat2Bit benchmarking suite and mirrors the backend report pipeline —
          classification performance, model complexity, and inference latency across the full optimization ladder.
        </p>
      </div>

      {/* Ladder selector */}
      <div>
        <p className="mb-4 text-sm font-semibold uppercase tracking-wider text-slate-500">Optimization ladder</p>
        <div className="flex flex-wrap gap-2">
          {reports.map((r, i) => {
            const m = meta(r.metadata.model_name)!;
            const active = selected?.metadata.model_name === r.metadata.model_name;
            return (
              <button
                key={r.metadata.model_name}
                onClick={() => onSelectName(r.metadata.model_name)}
                className={cn(
                  'flex flex-1 min-w-[160px] items-center gap-3 rounded-2xl border p-4 text-left transition-all',
                  active
                    ? 'border-rose-200 bg-rose-50/60 ring-2 ring-rose-200'
                    : 'border-slate-200 bg-white hover:border-slate-300 hover:shadow-sm'
                )}
              >
                <span
                  className="grid h-8 w-8 shrink-0 place-items-center rounded-full text-xs font-bold text-white"
                  style={{ background: MODEL_COLORS[r.metadata.model_name as keyof typeof MODEL_COLORS] ?? '#e11d48' }}
                >
                  {i + 1}
                </span>
                <span className="min-w-0">
                  <span className="block truncate text-sm font-semibold text-slate-900">{m.label}</span>
                  <span className="block text-xs text-slate-500">{m.tag}</span>
                </span>
                {active && <Check className="ml-auto h-4 w-4 shrink-0 text-rose-500" />}
              </button>
            );
          })}
        </div>
      </div>

      {loading || !selected ? (
        <div className="flex h-64 items-center justify-center text-slate-400">Loading metrics…</div>
      ) : (
        <>
          {/* Selected model: key metrics */}
          <section>
            <div className="mb-6 flex flex-col gap-1 sm:flex-row sm:items-end sm:justify-between">
              <div>
                <h2 className="text-2xl font-bold tracking-tight text-slate-900">
                  {meta(selected.metadata.model_name)?.label}
                </h2>
                <p className="mt-1 max-w-3xl text-slate-600">{meta(selected.metadata.model_name)?.description}</p>
              </div>
              <span className="inline-flex w-max items-center gap-1.5 rounded-full bg-slate-100 px-3 py-1 text-xs font-medium text-slate-600">
                <Gauge className="h-3.5 w-3.5" /> {selected.dataset_info.split}
              </span>
            </div>

            <div className="grid grid-cols-2 gap-3 md:grid-cols-5">
              <Kpi label="Accuracy" value={pct(selected.model_evaluation.accuracy)} accent="text-slate-900" />
              <Kpi label="F1 Score" value={pct(selected.model_evaluation.f1_score)} accent="text-indigo-600" />
              <Kpi label="AMI Sensitivity" value={pct(selected.model_evaluation.ami_sensitivity)} accent="text-emerald-600" />
              <Kpi label="AMI +Predictivity" value={pct(selected.model_evaluation.ami_positive_predictivity)} accent="text-rose-600" />
              <Kpi label="AMI Effectiveness" value={pct(selected.model_evaluation.ami_effectiveness)} accent="text-purple-600" />
            </div>
          </section>

          {/* Distribution charts */}
          <section className="grid gap-6 lg:grid-cols-2">
            <div className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm">
              <div className="mb-2 flex items-center gap-2">
                <Crosshair className="h-4 w-4 text-rose-500" />
                <h3 className="font-semibold text-slate-900">Metric Radar</h3>
              </div>
              <p className="mb-4 text-sm text-slate-500">Balanced view of classification &amp; AAMI performance.</p>
              <MetricRadar report={selected} color={MODEL_COLORS[selected.metadata.model_name as keyof typeof MODEL_COLORS]} />
            </div>
            <div className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm">
              <div className="mb-2 flex items-center gap-2">
                <Timer className="h-4 w-4 text-sky-500" />
                <h3 className="font-semibold text-slate-900">Inference Latency Distribution</h3>
              </div>
              <p className="mb-4 text-sm text-slate-500">
                Single-sample latency, batch=1 · mean {ms(selected.summary.latency_performance.single_sample_latency_ms)} · p95{' '}
                {ms(selected.summary.latency_performance.latency_p95_ms)}
              </p>
              <LatencyDistributionChart report={selected} />
            </div>
          </section>

          {/* Confusion matrix + recommendations */}
          <section className="grid gap-6 lg:grid-cols-5">
            <div className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm lg:col-span-3">
              <div className="mb-2 flex items-center gap-2">
                <Activity className="h-4 w-4 text-rose-500" />
                <h3 className="font-semibold text-slate-900">Confusion Matrix</h3>
              </div>
              <p className="mb-4 text-sm text-slate-500">
                {int(selected.dataset_info.samples)} samples · Normal vs Arrhythmia
              </p>
              <ConfusionMatrix report={selected} />
            </div>

            <div className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm lg:col-span-2">
              <div className="mb-2 flex items-center gap-2">
                <ListChecks className="h-4 w-4 text-emerald-500" />
                <h3 className="font-semibold text-slate-900">Recommendations</h3>
              </div>
              <p className="mb-4 text-sm text-slate-500">Auto-generated by the backend report generator.</p>
              <ul className="space-y-3">
                {selected.recommendations.map((r, i) => (
                  <li key={i} className="flex gap-2.5 rounded-2xl bg-slate-50 p-3 text-sm leading-relaxed text-slate-700">
                    <span className="mt-0.5 grid h-5 w-5 shrink-0 place-items-center rounded-full bg-emerald-100 text-emerald-600">
                      <Check className="h-3 w-3" />
                    </span>
                    {r}
                  </li>
                ))}
              </ul>
            </div>
          </section>

          {/* Cross-model comparison */}
          <section>
            <div className="mb-6">
              <p className="text-sm font-semibold uppercase tracking-wider text-slate-500">Model comparison</p>
              <h2 className="mt-2 text-2xl font-bold tracking-tight text-slate-900">
                Accuracy, size &amp; speed across the ladder
              </h2>
            </div>

            <div className="grid gap-6 lg:grid-cols-2">
              <div className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm">
                <h3 className="mb-1 flex items-center gap-2 font-semibold text-slate-900">
                  <Layers className="h-4 w-4 text-rose-500" /> Accuracy &amp; F1
                </h3>
                <AccuracyChart data={comparisonPoints} />
              </div>
              <div className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm">
                <h3 className="mb-1 flex items-center gap-2 font-semibold text-slate-900">
                  <Timer className="h-4 w-4 text-sky-500" /> Latency vs Size
                </h3>
                <EfficiencyChart data={comparisonPoints} />
              </div>
            </div>

            <div className="mt-6 rounded-3xl border border-slate-200 bg-white p-6 shadow-sm">
              <h3 className="mb-1 flex items-center gap-2 font-semibold text-slate-900">
                <Sparkles className="h-4 w-4 text-emerald-500" /> Throughput
              </h3>
              <ThroughputChart data={throughputData} />
            </div>
          </section>

          {/* Full table */}
          <section className="rounded-3xl border border-slate-200 bg-white shadow-sm">
            <div className="border-b border-slate-200 p-6">
              <h3 className="font-semibold text-slate-900">Full benchmark table</h3>
              <p className="mt-1 text-sm text-slate-500">Every metric exactly as produced by the backend report generator.</p>
            </div>
            <div className="overflow-x-auto">
              <table className="min-w-full divide-y divide-slate-200 text-sm">
                <thead className="bg-slate-50">
                  <tr className="text-left text-xs font-semibold uppercase tracking-wider text-slate-500">
                    <th className="px-5 py-3">Model</th>
                    <th className="px-3 py-3">Acc</th>
                    <th className="px-3 py-3">F1</th>
                    <th className="px-3 py-3">Se</th>
                    <th className="px-3 py-3">+P</th>
                    <th className="px-3 py-3">Eff</th>
                    <th className="px-3 py-3">Spec</th>
                    <th className="px-3 py-3">Latency</th>
                    <th className="px-3 py-3">p95</th>
                    <th className="px-3 py-3">Throughput</th>
                    <th className="px-3 py-3">Params</th>
                    <th className="px-3 py-3">Size (INT8)</th>
                    <th className="px-3 py-3">FLOPs</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-100">
                  {reports.map((r) => {
                    const m = meta(r.metadata.model_name)!;
                    const eval_ = r.model_evaluation;
                    return (
                      <tr key={r.metadata.model_name} className="transition-colors hover:bg-slate-50">
                        <td className="px-5 py-3 font-medium text-slate-900">
                          <span className="mr-2 inline-block h-2 w-2 rounded-full" style={{ background: MODEL_COLORS[r.metadata.model_name as keyof typeof MODEL_COLORS] ?? '#e11d48' }} />
                          {m.label}
                        </td>
                        <td className="px-3 py-3 tabular-nums">{pct(eval_.accuracy)}</td>
                        <td className="px-3 py-3 tabular-nums">{pct(eval_.f1_score)}</td>
                        <td className="px-3 py-3 tabular-nums">{pct(eval_.ami_sensitivity)}</td>
                        <td className="px-3 py-3 tabular-nums">{pct(eval_.ami_positive_predictivity)}</td>
                        <td className="px-3 py-3 tabular-nums">{pct(eval_.ami_effectiveness)}</td>
                        <td className="px-3 py-3 tabular-nums">{pct(eval_.specificity)}</td>
                        <td className="px-3 py-3 tabular-nums">{ms(r.summary.latency_performance.single_sample_latency_ms)}</td>
                        <td className="px-3 py-3 tabular-nums">{ms(r.summary.latency_performance.latency_p95_ms)}</td>
                        <td className="px-3 py-3 tabular-nums">{int(r.summary.latency_performance.throughput_samples_per_sec)}/s</td>
                        <td className="px-3 py-3 tabular-nums">{params(r.complexity_analysis.parameters.total_parameters)}</td>
                        <td className="px-3 py-3 tabular-nums">{mb(r.complexity_analysis.memory_size.int8_mb)}</td>
                        <td className="px-3 py-3 tabular-nums">{flops(r.complexity_analysis.computational_complexity.total_flops)}</td>
                      </tr>
                    );
                  })}
                </tbody>
              </table>
            </div>
          </section>
        </>
      )}
    </div>
  );
}

function Kpi({ label, value, accent }: { label: string; value: string; accent: string }) {
  return (
    <div className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm">
      <p className="text-xs font-medium uppercase tracking-wide text-slate-500">{label}</p>
      <p className={cn('mt-1.5 text-2xl font-bold tabular-nums', accent)}>{value}</p>
    </div>
  );
}
