"""
Training script for Beat2Bit (baseline). Supports two modes:
- smoke mode (default): quick no-op that verifies the script runs without heavy deps (keeps CI fast)
- full mode: trains a small 1D CNN using TensorFlow/Keras on data/processed synthetic data

Usage examples:
- Smoke mode (default): python -m src.training.train
- Full mode: python -m src.training.train --full --epochs 5
"""

import os
import argparse
import numpy as np

DATA_DIR = os.path.join(os.path.dirname(__file__), '..', '..', 'data', 'processed')
MODEL_DIR = os.path.join(os.path.dirname(__file__), '..', '..', 'models', 'saved')


def smoke():
    print("Running smoke mode — no heavy dependencies. Create synthetic data with small sample and exit.")
    # Ensure processed folder exists
    os.makedirs(DATA_DIR, exist_ok=True)
    os.makedirs(MODEL_DIR, exist_ok=True)
    # write a tiny placeholder file to indicate smoke passed
    with open(os.path.join(MODEL_DIR, 'smoke.txt'), 'w') as f:
        f.write('smoke OK')
    print("Smoke artifacts written to models/saved/")


def full_train(epochs=10, batch_size=16):
    try:
        import tensorflow as tf
        from tensorflow import keras
        from tensorflow.keras import layers
    except Exception as e:
        print("TensorFlow is required for full training mode. Install TensorFlow or run in smoke mode.")
        raise

    # Load dataset generated by data/generate_synthetic.py
    X_train = np.load(os.path.join(DATA_DIR, 'train.npy'))
    y_train = np.load(os.path.join(DATA_DIR, 'train_labels.npy'))
    X_val = np.load(os.path.join(DATA_DIR, 'val.npy'))
    y_val = np.load(os.path.join(DATA_DIR, 'val_labels.npy'))

    # Add channel dimension
    X_train = X_train[..., np.newaxis]
    X_val = X_val[..., np.newaxis]

    input_shape = X_train.shape[1:]
    model = keras.Sequential([
        layers.Input(shape=input_shape),
        layers.Conv1D(8, 5, activation='relu', padding='same'),
        layers.MaxPool1D(2),
        layers.Conv1D(16, 5, activation='relu', padding='same'),
        layers.GlobalAveragePooling1D(),
        layers.Dense(16, activation='relu'),
        layers.Dense(1, activation='sigmoid')
    ])

    model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
    model.summary()

    model.fit(X_train, y_train, validation_data=(X_val, y_val), epochs=epochs, batch_size=batch_size)

    os.makedirs(MODEL_DIR, exist_ok=True)
    # Save Keras model and a small TFLite placeholder if tflite converter available
    model_path = os.path.join(MODEL_DIR, 'baseline.h5')
    model.save(model_path)
    print(f"Saved Keras model to {model_path}")

    try:
        converter = tf.lite.TFLiteConverter.from_keras_model(model)
        tflite_model = converter.convert()
        tflite_path = os.path.join(MODEL_DIR, 'model.tflite')
        with open(tflite_path, 'wb') as f:
            f.write(tflite_model)
        print(f"Saved TFLite model to {tflite_path}")
    except Exception as e:
        print(f"TFLite conversion failed or not available: {e}")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--full', action='store_true', help='Run full training (requires TensorFlow)')
    parser.add_argument('--epochs', type=int, default=5)
    parser.add_argument('--batch-size', type=int, default=16)
    args = parser.parse_args()

    if not args.full:
        smoke()
    else:
        full_train(epochs=args.epochs, batch_size=args.batch_size)


if __name__ == '__main__':
    main()
